blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/igorxut/rapidfuzz-collections/discussions
    about: For usage questions and general discussion, please use GitHub Discussions.
